### ISSUE TITLE
视频输出问题

### ISSUE THREAD

**Issue by loyneshunter** [fanghon/lpr#2]
您好，尝试使用lpr.py 运行你提供的test.MP4进行视频测试，输出文件是一个5kb的文件，无法打开，您觉得是哪里出了问题？

**Comment by fanghon** [comment]
根据使用说明第5点，经测试，lpr.py运行正常，没发现你说的问题，命令是：python lpr.py --video=test.mp4
要注意大小写。
----- 原始邮件 -----
发件人：loyneshunter <notifications@github.com>
收件人：fanghon/lpr <lpr@noreply.github.com>
抄送人：Subscribed <subscribed@noreply.github.com>
主题：[fanghon/lpr]_视频输出问题_(#2)
日期：2020年04月27日 17点59分



您好，尝试使用lpr.py 运行你提供的test.MP4进行视频测试，输出文件是一个5kb的文件，无法打开，您觉得是哪里出了问题？



&mdash;
